### ISSUE TITLE
Can you provide the Appendix you mentioned in the paper?

### ISSUE THREAD

**Issue by Lukangkang123** [gimpong/AAAI22-MeCoQ#1]
In your paper, you said "We proof Proposition 1 in Appendix”, but I can't find the appendix on neither arXiv nor AAAI. So, can you provide the Appendix you mentioned in your paper? Or provide detailed proof of Proposition 1.

**Comment by gimpong** [comment]
Hello, below is the proof of Proposition 1.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/47932369/166108605-8e503026-2391-4d42-9ea5-a27bfcf69b12.png">

**Comment by Lukangkang123** [comment]
> Hello, below is the proof of Proposition 1.
> 
> <img alt="image" width="806" src="https://user-images.githubusercontent.com/47932369/166108605-8e503026-2391-4d42-9ea5-a27bfcf69b12.png">

Thank you~~~
